# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  title: Tinker-api
  version: "0.0.1"

host: api.tinkerpatch.com
schemes:
  - https
produces:
  - application/json

paths:
  /register:
    post:
      description: |
        "register a account with password"
      parameters:
        - name: user
          in: body
          description: login user info
          required: true
          schema:
            $ref: '#/de***REMOVED***nitions/loginUser'
      responses:
        200:
          description: return the access_token
          schema:
            type: object
            properties:
              token:
                type: string


################################################################################
#                                 De***REMOVED***nitions                                  #
################################################################################
de***REMOVED***nitions:
  loginUser:
    type: object
    properties:
      username:
        type: string
        require: true
      password:
        type: string
        require: true