package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*EmailLogin email login

swagger:model emailLogin
*/
type EmailLogin struct {

	/* email
	 */
	Email *string `json:"email,omitempty"`

	/* password

	Required: true
	*/
	Password string `json:"password"`

	/* rkey

	Required: true
	*/
	Rkey string `json:"rkey"`
}

// Validate validates this email login
func (m *EmailLogin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRkey(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EmailLogin) validatePassword(formats strfmt.Registry) error {

	if err := validate.RequiredString("password", "body", string(m.Password)); err != nil {
		return err
	}

	return nil
}

func (m *EmailLogin) validateRkey(formats strfmt.Registry) error {

	if err := validate.RequiredString("rkey", "body", string(m.Rkey)); err != nil {
		return err
	}

	return nil
}
