package models

// This ***REMOVED***le was generated by the swagger tool.
// Editing this ***REMOVED***le might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
***REMOVED***

/*RegisterInfo register info

swagger:model registerInfo
*/
type RegisterInfo struct {

	/* email

	Required: true
	*/
	Email string `json:"email"`

	/* password

	Required: true
	Min Length: 6
	*/
	Password string `json:"password"`

	/* username

	Required: true
	*/
	Username string `json:"username"`
}

// Validate validates this register info
func (m *RegisterInfo***REMOVED*** Validate(formats strfmt.Registry***REMOVED*** error {
	var res []error

	if err := m.validateEmail(formats***REMOVED***; err != nil {
		// prop
		res = append(res, err***REMOVED***
	}

	if err := m.validatePassword(formats***REMOVED***; err != nil {
		// prop
		res = append(res, err***REMOVED***
	}

	if err := m.validateUsername(formats***REMOVED***; err != nil {
		// prop
		res = append(res, err***REMOVED***
	}

	if len(res***REMOVED*** > 0 {
		return errors.CompositeValidationError(res...***REMOVED***
	}
	return nil
}

func (m *RegisterInfo***REMOVED*** validateEmail(formats strfmt.Registry***REMOVED*** error {

	if err := validate.RequiredString("email", "body", string(m.Email***REMOVED******REMOVED***; err != nil {
		return err
	}

	return nil
}

func (m *RegisterInfo***REMOVED*** validatePassword(formats strfmt.Registry***REMOVED*** error {

	if err := validate.RequiredString("password", "body", string(m.Password***REMOVED******REMOVED***; err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", string(m.Password***REMOVED***, 6***REMOVED***; err != nil {
		return err
	}

	return nil
}

func (m *RegisterInfo***REMOVED*** validateUsername(formats strfmt.Registry***REMOVED*** error {

	if err := validate.RequiredString("username", "body", string(m.Username***REMOVED******REMOVED***; err != nil {
		return err
	}

	return nil
}
