package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*RegisterInfo register info

swagger:model registerInfo
*/
type RegisterInfo struct {

	/* email

	Required: true
	*/
	Email string `json:"email"`

	/* password

	Required: true
	Min Length: 6
	*/
	Password string `json:"password"`

	/* username

	Required: true
	*/
	Username string `json:"username"`
}

// Validate validates this register info
func (m *RegisterInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterInfo) validateEmail(formats strfmt.Registry) error {

	if err := validate.RequiredString("email", "body", string(m.Email)); err != nil {
		return err
	}

	return nil
}

func (m *RegisterInfo) validatePassword(formats strfmt.Registry) error {

	if err := validate.RequiredString("password", "body", string(m.Password)); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", string(m.Password), 6); err != nil {
		return err
	}

	return nil
}

func (m *RegisterInfo) validateUsername(formats strfmt.Registry) error {

	if err := validate.RequiredString("username", "body", string(m.Username)); err != nil {
		return err
	}

	return nil
}
