package models

// This ***REMOVED***le was generated by the swagger tool.
// Editing this ***REMOVED***le might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
***REMOVED***

/*RetStatus ret status

swagger:model retStatus
*/
type RetStatus struct {

	/* code
	 */
	Code *int64 `json:"code,omitempty"`

	/* data
	 */
	Data interface{} `json:"data,omitempty"`

	/* message
	 */
	Message *string `json:"message,omitempty"`

	/* status

	Required: true
	*/
	Status string `json:"status"`
}

// Validate validates this ret status
func (m *RetStatus***REMOVED*** Validate(formats strfmt.Registry***REMOVED*** error {
	var res []error

	if err := m.validateStatus(formats***REMOVED***; err != nil {
		// prop
		res = append(res, err***REMOVED***
	}

	if len(res***REMOVED*** > 0 {
		return errors.CompositeValidationError(res...***REMOVED***
	}
	return nil
}

func (m *RetStatus***REMOVED*** validateStatus(formats strfmt.Registry***REMOVED*** error {

	if err := validate.RequiredString("status", "body", string(m.Status***REMOVED******REMOVED***; err != nil {
		return err
	}

	return nil
}
