package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*RetStatus ret status

swagger:model retStatus
*/
type RetStatus struct {

	/* code
	 */
	Code *int64 `json:"code,omitempty"`

	/* data
	 */
	Data interface{} `json:"data,omitempty"`

	/* message
	 */
	Message *string `json:"message,omitempty"`

	/* status

	Required: true
	*/
	Status string `json:"status"`
}

// Validate validates this ret status
func (m *RetStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RetStatus) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", string(m.Status)); err != nil {
		return err
	}

	return nil
}
